version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: tiqets_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    volumes:
      - ./data:/app/data
      - ./backend:/app/backend
    environment:
      DOCKER_MODE: "true"
      DATABASE_URL: postgresql://admin:admin@db:5432/tiqets_db
      FLASK_ENV: development
      FLASK_DEBUG: 1
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL_DOCKER: http://backend:5000/api
      VITE_API_URL: http://localhost:5000/api
    depends_on:
      - backend

volumes:
  postgres_data: