"""Initial migration

Revision ID: 87acfc8a0055
Revises: 
Create Date: 2025-01-05 14:40:50.553293

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "87acfc8a0055"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_customer_id", "orders", ["customer_id"], unique=False)
    op.create_table(
        "barcodes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("barcode_value", sa.String(length=255), nullable=True),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("is_used", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("barcode_value"),
    )
    op.create_index("idx_barcode_value", "barcodes", ["barcode_value"], unique=True)
    op.create_index("idx_order_id", "barcodes", ["order_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_order_id", table_name="barcodes")
    op.drop_index("idx_barcode_value", table_name="barcodes")
    op.drop_table("barcodes")
    op.drop_index("idx_customer_id", table_name="orders")
    op.drop_table("orders")
    op.drop_table("customers")
    # ### end Alembic commands ###
