name: Deploy

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success' && 
      github.event.workflow_run.event == 'pull_request' && 
      github.event.workflow_run.merged == true
    
    steps:
    - name: Deploy to Development
      if: github.ref == 'refs/heads/develop'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEV_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /opt/tiqets
          docker-compose -f dev/docker-compose.yml pull
          just migrate-dev
          just restart-dev
          
    - name: Deploy to Production
      if: github.ref == 'refs/heads/main'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PROD_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /opt/tiqets
          docker-compose -f prod/docker-compose.yml pull
          just migrate
          just restart